[package]
name = "aoc-rust"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "aoc-rust"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
regex = "1.12.2"
itertools = "0.12"
rayon = "1.10"
once_cell = "1.21.3"
good_lp = "1.5"
